version: '3.4'

networks:
  dev:
    driver: bridge

services:
  demo-app:
    image: docker.io/library/chatchirp
    depends_on:
      - "app_db"
    container_name: chatchirp-services
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=user;Password=secret;Server=app_db;Port=5432;Database=Chatchirp;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    volumes: 
      - C:/Users/quinn/Desktop/Code/Web/ChatChirp/ChatChirpBack/ChatChirp/ChatChirp/Services/Ai:/ChatChirp/Services/Ai
    networks:
      - dev
  app_db:
    image: postgres:15
    container_name: chatchirp_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=Chatchirp
    ports:
      - "15433:5432"
    restart: always
    volumes: 
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data:
